---
- name: Copy core-site.xml
  template: src=core-site.xml.j2 dest={{ hadoop_cofig_path }}/core-site.xml

- name: Copy hdfs-site.xml
  template: src=hdfs-site.xml.j2 dest={{ hadoop_cofig_path }}/hdfs-site.xml

- name: Copy mapred-site.xml
  template: src=mapred-site.xml.j2 dest={{ hadoop_cofig_path }}/mapred-site.xml

- name: Copy yarn-site.xml
  template: src=yarn-site.xml.j2 dest={{ hadoop_cofig_path }}/yarn-site.xml

- name: "Copy Hadoop workers"
  template: src=masters.j2 dest={{ hadoop_cofig_path }}/masters

- name: "Copy Hadoop workers"
  template: src=slaves.j2 dest={{ hadoop_cofig_path }}/slaves

- name: "Copy Hadoop Env Script"
  template: src=hadoop-env.sh.j2 dest=/etc/profile.d/hadoop-env.sh

- name: Set Hadoop Env
  shell: source /etc/profile.d/hadoop-env.sh