---
- name: Download hadoop distributed
  get_url:
    url: https://archive.apache.org/dist/hadoop/core/hadoop-2.7.7/hadoop-2.7.7.tar.gz
    dest: /opt
- name: Unarchive hadoop distributed
  unarchive:
    src: "/opt/{{ hadoop_tar }}"
    dest: "{{ hadoop_path }}"