---
- name: Includes base variables
  include_vars:
    dir: vars
- include_tasks: pre_deploy.yml
- include_tasks: install_hdfs.yml
- include_tasks: config_hadoop.yml
- include_tasks: run_hadoop_cluster.yml