---
- name: Hadoop format
  command: hdfs namenode -format -nonInteractive -force
  delegate_to: "{{ item }}"
  with_items: "{{ groups['master'] }}"
  run_once: true
- name: Hadoop run
  command: start-all.sh
  delegate_to: "{{ item }}"
  with_items: "{{ groups['master'] }}"
  run_once: true