---
# hadoop url download
hadoop_url: "https://archive.apache.org/dist/hadoop/core/hadoop-2.7.7/hadoop-2.7.7.tar.gz"
hadoop_tar: "hadoop-2.7.7.tar.gz"
# hadoop config
hadoop_version: "2.7.7"
hadoop_port: 9000
hadoop_path: "/opt/hadoop"
hadoop_cofig_path: "/opt/hadoop/hadoop-{{ hadoop_version }}/etc/hadoop"
hadoop_dfs_name: "/opt/hadoop/dfs/name"
hadoop_dfs_data: "/opt/hadoop/dfs/data"
hadoop_log_path: "/opt/hadoop/logs"
hadoop_tmp_dir: "{{ hadoop_path }}/tmp"
dfs_namenode_httpport: 9001


# yarn config
yarn_resourcemanager_port: 8040
yarn_resourcemanager_scheduler_port: 8030
yarn_resourcemanager_webapp_port: 8088
yarn_resourcemanager_tracker_port: 8025
yarn_resourcemanager_admin_port: 8141

hadoop_create_path:
  - "{{ hadoop_path }}"
  - "{{ hadoop_dfs_name }}"
  - "{{ hadoop_dfs_data }}"
  - "{{ hadoop_log_path }}"
  - "{{ hadoop_tmp_dir }}"

core_site_properties:
    - {
        "name" : "fs.defaultFS",
        "value" : "hdfs://{{ master }}:{{ hadoop_port }}"
    }
    - {
        "name" : "hadoop.tmp.dir",
        "value" : "file:{{ hadoop_tmp_dir }}"
    }
    - {
        "name" : "hadoop.proxyuser.hadoop.hosts",
        "value" : "*"
    }
    - {
        "name" : "hadoop.proxyuser.hadoop.groups",
        "value" : "*"
    }
hdfs_site_properties:
    - {
        "name" : "dfs.namenode.secondary.http-address",
        "value" : "{{ master }}:{{ dfs_namenode_httpport }}"
    }
    - {
        "name" : "dfs.namenode.name.dir",
        "value" : "file:{{ hadoop_dfs_name }}"
    }
    - {
        "name" : "dfs.namenode.data.dir",
        "value" : "file:{{ hadoop_dfs_data }}"
    }
    - {
        "name" : "dfs.replication",
        "value" : "1"
    }
    - {
        "name" : "dfs.webhdfs.enabled",
        "value" : "true"
    }
mapred_site_properties:
    - {
        "name" : "mapreduce.framework.name",
        "value" : "yarn"
    }
    - {
        "name" : "mapreduce.admin.user.env",
        "value" : "HADOOP_MAPRED_HOME=$HADOOP_COMMON_HOME"
    }
    - {
        "name" : "yarn.app.mapreduce.am.env",
        "value" : "HADOOP_MAPRED_HOME=$HADOOP_COMMON_HOME"
    }
yarn_site_properties:
    - {
       "name" : "yarn.resourcemanager.address",
       "value" : "{{ master }}:{{ yarn_resourcemanager_port  }}"
    }
    - {
       "name" : "yarn.resourcemanager.scheduler.address",
       "value" : "{{ master }}:{{ yarn_resourcemanager_scheduler_port }}"
    }
    - {
        "name" : "yarn.resourcemanager.webapp.address",
        "value" : "{{ master }}:{{ yarn_resourcemanager_webapp_port }}"
    }
    - {
        "name" : "yarn.resourcemanager.resource-tracker.address",
        "value" : "{{ master }}:{{ yarn_resourcemanager_tracker_port }}"
    }
    - {
        "name" : "yarn.resourcemanager.admin.address",
        "value" : "{{ master }}:{{ yarn_resourcemanager_admin_port }}"
    }
    - {
        "name" : "yarn.nodemanager.aux-services",
        "value" : "mapreduce_shuffle"
    }
    - {
        "name" : "yarn.nodemanager.aux-services.mapreduce.shuffle.class",
        "value" : "org.apache.hadoop.mapred.ShuffleHandler"
    }