---
- name: Install java openJDK
  yum:
    name: "{{ item  }}"
    state: installed
    update_cache: true
  with_items:
    - epel-release
    - java-1.8.0-openjdk.x86_64
    - java-1.8.0-openjdk-devel.x86_64
    - sshpass

- name: Copy Java Env Script
  template: src=java-env.sh.j2 dest=/etc/profile.d/java-env.sh

- name: Set Java Env
  shell: source /etc/profile.d/java-env.sh